services:
  backend:
    build: ./server
    container_name: backend
    restart: always
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=${MONGO_URI}
      - NODE_ENV=${NODE_ENV}
      - PORT=5001
      - CLIENT_URL=${CLIENT_URL}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - app-network
    # Add other env vars as needed

  frontend:
    build: ./client
    container_name: frontend
    restart: always
    volumes:
      - frontend-build:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - app-network

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - frontend-build:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
  frontend-build:
